/**
 * Generated by the WordPress Option Page generator
 * at http://jeremyhixon.com/wp-tools/option-page/
 */

class Donnes {
	private $donnees_options;

	public function __construct() {
		add_action( 'admin_menu', array( $this, 'donnees_add_plugin_page' ) );
		add_action( 'admin_init', array( $this, 'donnees_page_init' ) );
	}

	public function donnees_add_plugin_page() {
		add_menu_page(
			'Données', // page_title
			'Données', // menu_title
			'manage_options', // capability
			'donnees', // menu_slug
			array( $this, 'donnees_create_admin_page' ), // function
			'dashicons-admin-collapse', // icon_url
			3 // position
		);
	}

	public function donnees_create_admin_page() {
		$this->donnees_options = get_option( 'donnees_option_name' ); ?>

		<div class="wrap">
			<h2>Données</h2>
			<p>Données du site</p>
			<?php settings_errors(); ?>

			<form method="post" action="options.php">
				<?php
					settings_fields( 'donnees_option_group' );
					do_settings_sections( 'donnees-admin' );
					submit_button();
				?>
			</form>
		</div>
	<?php }

	public function donnees_page_init() {
		register_setting(
			'donnees_option_group', // option_group
			'donnees_option_name', // option_name
			array( $this, 'donnees_sanitize' ) // sanitize_callback
		);

		add_settings_section(
			'donnees_setting_section', // id
			'Settings', // title
			array( $this, 'donnees_section_info' ), // callback
			'donnees-admin' // page
		);

		add_settings_field(
			'votre_nom_0', // id
			'Votre nom', // title
			array( $this, 'votre_nom_0_callback' ), // callback
			'donnees-admin', // page
			'donnees_setting_section' // section
		);

		add_settings_field(
			'votre_prenom_1', // id
			'Votre prénom', // title
			array( $this, 'votre_prenom_1_callback' ), // callback
			'donnees-admin', // page
			'donnees_setting_section' // section
		);

		add_settings_field(
			'votre_adresse_2', // id
			'Votre Adresse', // title
			array( $this, 'votre_adresse_2_callback' ), // callback
			'donnees-admin', // page
			'donnees_setting_section' // section
		);

		add_settings_field(
			'votre_numero_de_telephone_3', // id
			'Votre Numero de téléphone', // title
			array( $this, 'votre_numero_de_telephone_3_callback' ), // callback
			'donnees-admin', // page
			'donnees_setting_section' // section
		);

		add_settings_field(
			'votre_numero_de_fax_4', // id
			'Votre Numero de Fax', // title
			array( $this, 'votre_numero_de_fax_4_callback' ), // callback
			'donnees-admin', // page
			'donnees_setting_section' // section
		);

		add_settings_field(
			'votre_e_mail_5', // id
			'Votre E-mail', // title
			array( $this, 'votre_e_mail_5_callback' ), // callback
			'donnees-admin', // page
			'donnees_setting_section' // section
		);

		add_settings_field(
			'votre_specialite_6', // id
			'Votre Spécialite', // title
			array( $this, 'votre_specialite_6_callback' ), // callback
			'donnees-admin', // page
			'donnees_setting_section' // section
		);

		add_settings_field(
			'l_equipe_7', // id
			'L\'équipe', // title
			array( $this, 'l_equipe_7_callback' ), // callback
			'donnees-admin', // page
			'donnees_setting_section' // section
		);

		add_settings_field(
			'le_cabinet_8', // id
			'Le cabinet', // title
			array( $this, 'le_cabinet_8_callback' ), // callback
			'donnees-admin', // page
			'donnees_setting_section' // section
		);
	}

	public function donnees_sanitize($input) {
		$sanitary_values = array();
		if ( isset( $input['votre_nom_0'] ) ) {
			$sanitary_values['votre_nom_0'] = sanitize_text_field( $input['votre_nom_0'] );
		}

		if ( isset( $input['votre_prenom_1'] ) ) {
			$sanitary_values['votre_prenom_1'] = sanitize_text_field( $input['votre_prenom_1'] );
		}

		if ( isset( $input['votre_adresse_2'] ) ) {
			$sanitary_values['votre_adresse_2'] = esc_textarea( $input['votre_adresse_2'] );
		}

		if ( isset( $input['votre_numero_de_telephone_3'] ) ) {
			$sanitary_values['votre_numero_de_telephone_3'] = sanitize_text_field( $input['votre_numero_de_telephone_3'] );
		}

		if ( isset( $input['votre_numero_de_fax_4'] ) ) {
			$sanitary_values['votre_numero_de_fax_4'] = sanitize_text_field( $input['votre_numero_de_fax_4'] );
		}

		if ( isset( $input['votre_e_mail_5'] ) ) {
			$sanitary_values['votre_e_mail_5'] = sanitize_text_field( $input['votre_e_mail_5'] );
		}

		if ( isset( $input['votre_specialite_6'] ) ) {
			$sanitary_values['votre_specialite_6'] = sanitize_text_field( $input['votre_specialite_6'] );
		}

		if ( isset( $input['l_equipe_7'] ) ) {
			$sanitary_values['l_equipe_7'] = esc_textarea( $input['l_equipe_7'] );
		}

		if ( isset( $input['le_cabinet_8'] ) ) {
			$sanitary_values['le_cabinet_8'] = esc_textarea( $input['le_cabinet_8'] );
		}

		return $sanitary_values;
	}

	public function donnees_section_info() {
		
	}

	public function votre_nom_0_callback() {
		printf(
			'<input class="regular-text" type="text" name="donnees_option_name[votre_nom_0]" id="votre_nom_0" value="%s">',
			isset( $this->donnees_options['votre_nom_0'] ) ? esc_attr( $this->donnees_options['votre_nom_0']) : ''
		);
	}

	public function votre_prenom_1_callback() {
		printf(
			'<input class="regular-text" type="text" name="donnees_option_name[votre_prenom_1]" id="votre_prenom_1" value="%s">',
			isset( $this->donnees_options['votre_prenom_1'] ) ? esc_attr( $this->donnees_options['votre_prenom_1']) : ''
		);
	}

	public function votre_adresse_2_callback() {
		printf(
			'<textarea class="large-text" rows="5" name="donnees_option_name[votre_adresse_2]" id="votre_adresse_2">%s</textarea>',
			isset( $this->donnees_options['votre_adresse_2'] ) ? esc_attr( $this->donnees_options['votre_adresse_2']) : ''
		);
	}

	public function votre_numero_de_telephone_3_callback() {
		printf(
			'<input class="regular-text" type="text" name="donnees_option_name[votre_numero_de_telephone_3]" id="votre_numero_de_telephone_3" value="%s">',
			isset( $this->donnees_options['votre_numero_de_telephone_3'] ) ? esc_attr( $this->donnees_options['votre_numero_de_telephone_3']) : ''
		);
	}

	public function votre_numero_de_fax_4_callback() {
		printf(
			'<input class="regular-text" type="text" name="donnees_option_name[votre_numero_de_fax_4]" id="votre_numero_de_fax_4" value="%s">',
			isset( $this->donnees_options['votre_numero_de_fax_4'] ) ? esc_attr( $this->donnees_options['votre_numero_de_fax_4']) : ''
		);
	}

	public function votre_e_mail_5_callback() {
		printf(
			'<input class="regular-text" type="text" name="donnees_option_name[votre_e_mail_5]" id="votre_e_mail_5" value="%s">',
			isset( $this->donnees_options['votre_e_mail_5'] ) ? esc_attr( $this->donnees_options['votre_e_mail_5']) : ''
		);
	}

	public function votre_specialite_6_callback() {
		printf(
			'<input class="regular-text" type="text" name="donnees_option_name[votre_specialite_6]" id="votre_specialite_6" value="%s">',
			isset( $this->donnees_options['votre_specialite_6'] ) ? esc_attr( $this->donnees_options['votre_specialite_6']) : ''
		);
	}

	public function l_equipe_7_callback() {
		printf(
			'<textarea class="large-text" rows="5" name="donnees_option_name[l_equipe_7]" id="l_equipe_7">%s</textarea>',
			isset( $this->donnees_options['l_equipe_7'] ) ? esc_attr( $this->donnees_options['l_equipe_7']) : ''
		);
	}

	public function le_cabinet_8_callback() {
		printf(
			'<textarea class="large-text" rows="5" name="donnees_option_name[le_cabinet_8]" id="le_cabinet_8">%s</textarea>',
			isset( $this->donnees_options['le_cabinet_8'] ) ? esc_attr( $this->donnees_options['le_cabinet_8']) : ''
		);
	}

}
if ( is_admin() )
	$donnees = new Donnes();

/* 
 * Retrieve this value with:
 * $donnees_options = get_option( 'donnees_option_name' ); // Array of All Options
 * $votre_nom_0 = $donnees_options['votre_nom_0']; // Votre nom
 * $votre_prenom_1 = $donnees_options['votre_prenom_1']; // Votre prénom
 * $votre_adresse_2 = $donnees_options['votre_adresse_2']; // Votre Adresse
 * $votre_numero_de_telephone_3 = $donnees_options['votre_numero_de_telephone_3']; // Votre Numero de téléphone
 * $votre_numero_de_fax_4 = $donnees_options['votre_numero_de_fax_4']; // Votre Numero de Fax
 * $votre_e_mail_5 = $donnees_options['votre_e_mail_5']; // Votre E-mail
 * $votre_specialite_6 = $donnees_options['votre_specialite_6']; // Votre Spécialite
 * $l_equipe_7 = $donnees_options['l_equipe_7']; // L\'équipe
 * $le_cabinet_8 = $donnees_options['le_cabinet_8']; // Le cabinet
 */
